//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace PiKvmLibrary.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("PiKvmLibraryConfiguration", Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd", IsNullable=false)]
    public partial class PiKvmLibraryConfigurationType {
        
        private ConnectionsType connectionsField;
        
        private StandardEndpointsEnumType exampleEndpointsField;
        
        private bool exampleEndpointsFieldSpecified;
        
        /// <remarks/>
        public ConnectionsType Connections {
            get {
                return this.connectionsField;
            }
            set {
                this.connectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StandardEndpointsEnumType ExampleEndpoints {
            get {
                return this.exampleEndpointsField;
            }
            set {
                this.exampleEndpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExampleEndpointsSpecified {
            get {
                return this.exampleEndpointsFieldSpecified;
            }
            set {
                this.exampleEndpointsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Connections", Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd", IsNullable=false)]
    public partial class ConnectionsType {
        
        private ConnectionType[] connectionField;
        
        private string versionField;
        
        private bool enableSingleQuoteJsonField;
        
        private string defaultUserNamePromptHeaderField;
        
        private string defaultPasswordPromptHeaderField;
        
        private bool defaultPreferCookieAuthenticationField;
        
        private bool defaultIgnoreCertificateErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Connection", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConnectionType[] Connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableSingleQuoteJson {
            get {
                return this.enableSingleQuoteJsonField;
            }
            set {
                this.enableSingleQuoteJsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultUserNamePromptHeader {
            get {
                return this.defaultUserNamePromptHeaderField;
            }
            set {
                this.defaultUserNamePromptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultPasswordPromptHeader {
            get {
                return this.defaultPasswordPromptHeaderField;
            }
            set {
                this.defaultPasswordPromptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DefaultPreferCookieAuthentication {
            get {
                return this.defaultPreferCookieAuthenticationField;
            }
            set {
                this.defaultPreferCookieAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DefaultIgnoreCertificateErrors {
            get {
                return this.defaultIgnoreCertificateErrorsField;
            }
            set {
                this.defaultIgnoreCertificateErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class ConnectionType {
        
        private EndpointType[] endpointsField;
        
        private string nameField;
        
        private string baseURIField;
        
        private string userNamePromptHeaderField;
        
        private string passwordPromptHeaderField;
        
        private bool preferCookieAuthenticationField;
        
        private bool preferCookieAuthenticationFieldSpecified;
        
        private bool ignoreCertificateErrorsField;
        
        private bool ignoreCertificateErrorsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Endpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EndpointType[] Endpoints {
            get {
                return this.endpointsField;
            }
            set {
                this.endpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string BaseURI {
            get {
                return this.baseURIField;
            }
            set {
                this.baseURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserNamePromptHeader {
            get {
                return this.userNamePromptHeaderField;
            }
            set {
                this.userNamePromptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PasswordPromptHeader {
            get {
                return this.passwordPromptHeaderField;
            }
            set {
                this.passwordPromptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool PreferCookieAuthentication {
            get {
                return this.preferCookieAuthenticationField;
            }
            set {
                this.preferCookieAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferCookieAuthenticationSpecified {
            get {
                return this.preferCookieAuthenticationFieldSpecified;
            }
            set {
                this.preferCookieAuthenticationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IgnoreCertificateErrors {
            get {
                return this.ignoreCertificateErrorsField;
            }
            set {
                this.ignoreCertificateErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoreCertificateErrorsSpecified {
            get {
                return this.ignoreCertificateErrorsFieldSpecified;
            }
            set {
                this.ignoreCertificateErrorsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class EndpointType {
        
        private object itemField;
        
        private string nameField;
        
        private double endpointTimeout_SecField;
        
        private string userNamePromptHeaderField;
        
        private string passwordPromptHeaderField;
        
        private bool preferCookieAuthenticationField;
        
        private bool preferCookieAuthenticationFieldSpecified;
        
        private bool ignoreCertificateErrorsField;
        
        private bool ignoreCertificateErrorsFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HttpRequest", typeof(HttpEndpointType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Websocket", typeof(WebSocketType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double EndpointTimeout_Sec {
            get {
                return this.endpointTimeout_SecField;
            }
            set {
                this.endpointTimeout_SecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserNamePromptHeader {
            get {
                return this.userNamePromptHeaderField;
            }
            set {
                this.userNamePromptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PasswordPromptHeader {
            get {
                return this.passwordPromptHeaderField;
            }
            set {
                this.passwordPromptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool PreferCookieAuthentication {
            get {
                return this.preferCookieAuthenticationField;
            }
            set {
                this.preferCookieAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferCookieAuthenticationSpecified {
            get {
                return this.preferCookieAuthenticationFieldSpecified;
            }
            set {
                this.preferCookieAuthenticationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IgnoreCertificateErrors {
            get {
                return this.ignoreCertificateErrorsField;
            }
            set {
                this.ignoreCertificateErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoreCertificateErrorsSpecified {
            get {
                return this.ignoreCertificateErrorsFieldSpecified;
            }
            set {
                this.ignoreCertificateErrorsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class HttpEndpointType {
        
        private KeyValuePairType[] httpHeadersField;
        
        private KeyValuePairType[] querysField;
        
        private ContentsType contentsField;
        
        private ParameterType[] parametersField;
        
        private string nameField;
        
        private string endpointField;
        
        private HttpRequestEnumType httpMethodField;
        
        private string descriptionField;
        
        private bool hTTP_GenericLogEnabledField;
        
        private bool hTTP_HttpLogEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HttpHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePairType[] HttpHeaders {
            get {
                return this.httpHeadersField;
            }
            set {
                this.httpHeadersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Query", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePairType[] Querys {
            get {
                return this.querysField;
            }
            set {
                this.querysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContentsType Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ParameterType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HttpRequestEnumType HttpMethod {
            get {
                return this.httpMethodField;
            }
            set {
                this.httpMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HTTP_GenericLogEnabled {
            get {
                return this.hTTP_GenericLogEnabledField;
            }
            set {
                this.hTTP_GenericLogEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HTTP_HttpLogEnabled {
            get {
                return this.hTTP_HttpLogEnabledField;
            }
            set {
                this.hTTP_HttpLogEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class KeyValuePairType {
        
        private string nameField;
        
        private string valueField;
        
        private bool optionalField;
        
        private string descriptionField;
        
        public KeyValuePairType() {
            this.optionalField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class FFmpegConfigurationType {
        
        private string applicationPathField;
        
        private string applicationArgumentsField;
        
        private int outputBufferSizeField;
        
        private bool genericLogEnabledField;
        
        private bool ouputLogEnabledField;
        
        private bool streamOutput_TaskEnabledField;
        
        private bool errorStream_TaskEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationPath {
            get {
                return this.applicationPathField;
            }
            set {
                this.applicationPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationArguments {
            get {
                return this.applicationArgumentsField;
            }
            set {
                this.applicationArgumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OutputBufferSize {
            get {
                return this.outputBufferSizeField;
            }
            set {
                this.outputBufferSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool GenericLogEnabled {
            get {
                return this.genericLogEnabledField;
            }
            set {
                this.genericLogEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool OuputLogEnabled {
            get {
                return this.ouputLogEnabledField;
            }
            set {
                this.ouputLogEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool StreamOutput_TaskEnabled {
            get {
                return this.streamOutput_TaskEnabledField;
            }
            set {
                this.streamOutput_TaskEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ErrorStream_TaskEnabled {
            get {
                return this.errorStream_TaskEnabledField;
            }
            set {
                this.errorStream_TaskEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class PostProcessStreamType {
        
        private FFmpegConfigurationType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FFmpegConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FFmpegConfigurationType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class SettingCommandType {
        
        private string endpointNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndpointName {
            get {
                return this.endpointNameField;
            }
            set {
                this.endpointNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class WebSocketCommandType {
        
        private ParameterType[] parametersField;
        
        private string nameField;
        
        private string jsonTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ParameterType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string JsonTemplate {
            get {
                return this.jsonTemplateField;
            }
            set {
                this.jsonTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class ParameterType {
        
        private string nameField;
        
        private bool optionalField;
        
        private string valueTypeField;
        
        public ParameterType() {
            this.optionalField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class WebSocketType {
        
        private WebSocketCommandType[] wSCommandsField;
        
        private SettingCommandType[] settingCommandsField;
        
        private PostProcessStreamType postProcessStreamField;
        
        private string endpointField;
        
        private bool messageLogEnabledField;
        
        private bool genericLogEnabledField;
        
        private bool stream_TaskEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WsCommand", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WebSocketCommandType[] WSCommands {
            get {
                return this.wSCommandsField;
            }
            set {
                this.wSCommandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Command", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SettingCommandType[] SettingCommands {
            get {
                return this.settingCommandsField;
            }
            set {
                this.settingCommandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PostProcessStreamType PostProcessStream {
            get {
                return this.postProcessStreamField;
            }
            set {
                this.postProcessStreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MessageLogEnabled {
            get {
                return this.messageLogEnabledField;
            }
            set {
                this.messageLogEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool GenericLogEnabled {
            get {
                return this.genericLogEnabledField;
            }
            set {
                this.genericLogEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Stream_TaskEnabled {
            get {
                return this.stream_TaskEnabledField;
            }
            set {
                this.stream_TaskEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class ContentsBinaryType {
        
        private byte[] binaryBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] BinaryBase64 {
            get {
                return this.binaryBase64Field;
            }
            set {
                this.binaryBase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class ContentsStringType {
        
        private string stringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string String {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class ContentsDictionaryType {
        
        private KeyValuePairType[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KeyValuePairType[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public partial class ContentsType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContentBinary", typeof(ContentsBinaryType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ContentDictionary", typeof(ContentsDictionaryType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ContentString", typeof(ContentsStringType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public enum HttpRequestEnumType {
        
        /// <remarks/>
        GET,
        
        /// <remarks/>
        POST,
        
        /// <remarks/>
        PUT,
        
        /// <remarks/>
        DELETE,
        
        /// <remarks/>
        PATCH,
        
        /// <remarks/>
        HEAD,
        
        /// <remarks/>
        OPTIONS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PiKvmLibrary.local/PiKvmConnectionsConfigurationSchema.xsd")]
    public enum StandardEndpointsEnumType {
        
        /// <remarks/>
        Login_Endpoint,
        
        /// <remarks/>
        Logout_Endpoint,
        
        /// <remarks/>
        CheckAuth_Endpoint,
        
        /// <remarks/>
        Info_Endpoint,
        
        /// <remarks/>
        PrintText_Endpoint,
        
        /// <remarks/>
        SendKeyboardKey_Endpoint,
        
        /// <remarks/>
        SendKeyboardMultiKeyPress_Endpoint,
        
        /// <remarks/>
        HidInformation_Endpoint,
        
        /// <remarks/>
        StreamerInformation_Endpoint,
        
        /// <remarks/>
        MouseOutputType_Endpoint,
        
        /// <remarks/>
        MouseOutputAbsolute_Endpoint,
        
        /// <remarks/>
        MouseOutputRelative_Endpoint,
        
        /// <remarks/>
        MouseMoveRelative_Endpoint,
        
        /// <remarks/>
        MouseMoveAbsolute_Endpoint,
        
        /// <remarks/>
        MouseButton_Endpoint,
        
        /// <remarks/>
        MouseButtonState_Endpoint,
        
        /// <remarks/>
        H264_GOP_Endpoint,
        
        /// <remarks/>
        H264_Bitrate_Endpoint,
        
        /// <remarks/>
        API_Endpoint,
    }
}
