//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace PiKvmLibrary.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("StreamerInformation", Namespace="http://tempuri.org/StreamerInformationSchema.xsd", IsNullable=false)]
    public partial class StreamerInformationType {
        
        private ResultType resultField;
        
        private bool okField;
        
        /// <remarks/>
        public ResultType result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class ResultType {
        
        private FeaturesType featuresField;
        
        private LimitsType limitsField;
        
        private ParamsType paramsField;
        
        private SnapshotType snapshotField;
        
        private StreamerType streamerField;
        
        /// <remarks/>
        public FeaturesType features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
            }
        }
        
        /// <remarks/>
        public LimitsType limits {
            get {
                return this.limitsField;
            }
            set {
                this.limitsField = value;
            }
        }
        
        /// <remarks/>
        public ParamsType @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
            }
        }
        
        /// <remarks/>
        public SnapshotType snapshot {
            get {
                return this.snapshotField;
            }
            set {
                this.snapshotField = value;
            }
        }
        
        /// <remarks/>
        public StreamerType streamer {
            get {
                return this.streamerField;
            }
            set {
                this.streamerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class FeaturesType {
        
        private bool h264Field;
        
        private bool qualityField;
        
        private bool resolutionField;
        
        /// <remarks/>
        public bool h264 {
            get {
                return this.h264Field;
            }
            set {
                this.h264Field = value;
            }
        }
        
        /// <remarks/>
        public bool quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        public bool resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class ClientsStatType {
        
        private string client_idField;
        
        private string fpsField;
        
        private string bitrateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string client_id {
            get {
                return this.client_idField;
            }
            set {
                this.client_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string fps {
            get {
                return this.fpsField;
            }
            set {
                this.fpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class StreamType {
        
        private string clientsField;
        
        private ClientsStatType clients_statField;
        
        private string queued_fpsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string clients {
            get {
                return this.clientsField;
            }
            set {
                this.clientsField = value;
            }
        }
        
        /// <remarks/>
        public ClientsStatType clients_stat {
            get {
                return this.clients_statField;
            }
            set {
                this.clients_statField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string queued_fps {
            get {
                return this.queued_fpsField;
            }
            set {
                this.queued_fpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class ResolutionType {
        
        private string widthField;
        
        private string heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class SourceType {
        
        private string captured_fpsField;
        
        private string desired_fpsField;
        
        private bool onlineField;
        
        private ResolutionType resolutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string captured_fps {
            get {
                return this.captured_fpsField;
            }
            set {
                this.captured_fpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string desired_fps {
            get {
                return this.desired_fpsField;
            }
            set {
                this.desired_fpsField = value;
            }
        }
        
        /// <remarks/>
        public bool online {
            get {
                return this.onlineField;
            }
            set {
                this.onlineField = value;
            }
        }
        
        /// <remarks/>
        public ResolutionType resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class SinkType {
        
        private bool has_clientsField;
        
        /// <remarks/>
        public bool has_clients {
            get {
                return this.has_clientsField;
            }
            set {
                this.has_clientsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class SinksType {
        
        private SinkType h264Field;
        
        private SinkType jpegField;
        
        /// <remarks/>
        public SinkType h264 {
            get {
                return this.h264Field;
            }
            set {
                this.h264Field = value;
            }
        }
        
        /// <remarks/>
        public SinkType jpeg {
            get {
                return this.jpegField;
            }
            set {
                this.jpegField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class H264Type {
        
        private string bitrateField;
        
        private string fpsField;
        
        private string gopField;
        
        private bool onlineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string fps {
            get {
                return this.fpsField;
            }
            set {
                this.fpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string gop {
            get {
                return this.gopField;
            }
            set {
                this.gopField = value;
            }
        }
        
        /// <remarks/>
        public bool online {
            get {
                return this.onlineField;
            }
            set {
                this.onlineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class EncoderType {
        
        private string qualityField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class DrmType {
        
        private string fpsField;
        
        private bool liveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string fps {
            get {
                return this.fpsField;
            }
            set {
                this.fpsField = value;
            }
        }
        
        /// <remarks/>
        public bool live {
            get {
                return this.liveField;
            }
            set {
                this.liveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class StreamerType {
        
        private string instance_idField;
        
        private DrmType drmField;
        
        private EncoderType encoderField;
        
        private H264Type h264Field;
        
        private SinksType sinksField;
        
        private SourceType sourceField;
        
        private StreamType streamField;
        
        /// <remarks/>
        public string instance_id {
            get {
                return this.instance_idField;
            }
            set {
                this.instance_idField = value;
            }
        }
        
        /// <remarks/>
        public DrmType drm {
            get {
                return this.drmField;
            }
            set {
                this.drmField = value;
            }
        }
        
        /// <remarks/>
        public EncoderType encoder {
            get {
                return this.encoderField;
            }
            set {
                this.encoderField = value;
            }
        }
        
        /// <remarks/>
        public H264Type h264 {
            get {
                return this.h264Field;
            }
            set {
                this.h264Field = value;
            }
        }
        
        /// <remarks/>
        public SinksType sinks {
            get {
                return this.sinksField;
            }
            set {
                this.sinksField = value;
            }
        }
        
        /// <remarks/>
        public SourceType source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public StreamType stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class SnapshotType {
        
        private string savedField;
        
        /// <remarks/>
        public string saved {
            get {
                return this.savedField;
            }
            set {
                this.savedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class ParamsType {
        
        private string desired_fpsField;
        
        private string h264_bitrateField;
        
        private string h264_gopField;
        
        private string qualityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string desired_fps {
            get {
                return this.desired_fpsField;
            }
            set {
                this.desired_fpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string h264_bitrate {
            get {
                return this.h264_bitrateField;
            }
            set {
                this.h264_bitrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string h264_gop {
            get {
                return this.h264_gopField;
            }
            set {
                this.h264_gopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class RangeType {
        
        private string minField;
        
        private string maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/StreamerInformationSchema.xsd")]
    public partial class LimitsType {
        
        private RangeType desired_fpsField;
        
        private RangeType h264_bitrateField;
        
        private RangeType h264_gopField;
        
        /// <remarks/>
        public RangeType desired_fps {
            get {
                return this.desired_fpsField;
            }
            set {
                this.desired_fpsField = value;
            }
        }
        
        /// <remarks/>
        public RangeType h264_bitrate {
            get {
                return this.h264_bitrateField;
            }
            set {
                this.h264_bitrateField = value;
            }
        }
        
        /// <remarks/>
        public RangeType h264_gop {
            get {
                return this.h264_gopField;
            }
            set {
                this.h264_gopField = value;
            }
        }
    }
}
